--// Querie Desenvolvida por David Ponzenato
--//-- Objetivo consolidar toda entrada de Notas e publicar o resultado em um Painel Indicador de Procurement e Compliance. - Não alterar ! Esta fonte alimenta um painel BI. 
SELECT N.NRORG, ORG.NMORGANIZACAO, N.CDEMPRESA, N.NMEMPRESA, N.CDFILIAL, N.NMFILIAL,
   N.DTENTRSAID, N.DTEMISSAO, N.PERIODO, N.ANO, N.DSMES, N.NRMES, N.DTMES, N.TRIMES, N.NMTIPOOPER,
   N.NRNOTAFISC,   N.CDSERIEENTR,  N.IDTPIJURNF, N.NRLANCTONF, N.CDPRODUTO, N.NMPRODUTO, N.SGUNIDADE,
   N.DTORIGVENPAG, N.IDERROS, N.IDAVISOS, N.CDFILIEMIT, N.IDORIGDESTOP, N.NRINSJURNF AS CNPJ,
   N.NMFILFORCLIE AS FORNECEDOR, N.CDOPERGERA, N.QTDIASVENPAG, N.QTITEMPROD, N.VRUNITITEM,  N.VRNOTAFISC, N.VRTOTAL,
   N.VRTOTAITEM,
    (SELECT NVL(SUM(VRTOTIMPONF),0)
             FROM IMPOSNFTOT,IMPOSTO
             WHERE IMPOSNFTOT.CDIMPOSTO = IMPOSTO.CDIMPOSTONFE
              AND IMPOSTO.CDIMPOSTO = '30'
              AND IMPOSNFTOT.CDFILIAL = N.CDFILIAL
              AND IMPOSNFTOT.NRLANCTONF = N.NRLANCTONF
            ) VR_ISS,
	(SELECT NVL(SUM(VRTOTIMPONF),0)
             FROM IMPOSNFTOT,IMPOSTO
             WHERE IMPOSNFTOT.CDIMPOSTO = IMPOSTO.CDIMPOSTONFE
              AND IMPOSTO.CDIMPOSTO = '00'
              AND IMPOSNFTOT.CDFILIAL = N.CDFILIAL
              AND IMPOSNFTOT.NRLANCTONF = N.NRLANCTONF
            ) VR_ICMS,
	(SELECT NVL(SUM(VRTOTIMPONF),0)
             FROM IMPOSNFTOT,IMPOSTO
             WHERE IMPOSNFTOT.CDIMPOSTO = IMPOSTO.CDIMPOSTONFE
              AND IMPOSTO.CDIMPOSTO = '10'
              AND IMPOSNFTOT.CDFILIAL = N.CDFILIAL
              AND IMPOSNFTOT.NRLANCTONF = N.NRLANCTONF
            ) VR_IPI,
	(SELECT NVL(SUM(VRTOTIMPONF),0)
             FROM IMPOSNFTOT,IMPOSTO
             WHERE IMPOSNFTOT.CDIMPOSTO = IMPOSTO.CDIMPOSTO
              AND IMPOSTO.CDIMPOSTO = '50'
              AND IMPOSNFTOT.CDFILIAL = N.CDFILIAL
              AND IMPOSNFTOT.NRLANCTONF = N.NRLANCTONF
            ) VR_PIS,
	(SELECT NVL(SUM(VRTOTIMPONF),0)
             FROM IMPOSNFTOT,IMPOSTO
             WHERE IMPOSNFTOT.CDIMPOSTO = IMPOSTO.CDIMPOSTO
              AND IMPOSTO.CDIMPOSTO = '60'
              AND IMPOSNFTOT.CDFILIAL = N.CDFILIAL
              AND IMPOSNFTOT.NRLANCTONF = N.NRLANCTONF
            ) VR_COFINS,
    N.NMSUBPRODNIVEL
 FROM(SELECT DISTINCT EM.NRORG, EM.CDEMPRESA, EM.NMEMPRESA, F.CDFILIAL, DECODE(F.CDFILIAL, '', '', F.NMFILIAL) NMFILIAL,
       A.DTENTRSAID, A.DTEMISSAO, TO_CHAR(A.DTENTRSAID, 'MON/YYYY')AS PERIODO, TO_CHAR(A.DTENTRSAID, 'YYYY')AS ANO, TO_CHAR(A.DTENTRSAID, 'MON')AS DSMES,
       TO_CHAR(A.DTENTRSAID, 'MM')AS NRMES, TRUNC(A.DTENTRSAID, 'MM')AS DTMES, TO_CHAR(A.DTENTRSAID,'Q')||'° Trimestre'AS TRIMES, SUBSTR(C.NMTIPOOPER,1,14) AS NMTIPOOPER,
       A.NRNOTAFISC, A.CDSERIEENTR, A.IDTPIJURNF, A.NRINSJURNF,   A.NRLANCTONF, PR.CDPRODUTO, PR.NMPRODUTO, PR.SGUNIDADE, B.DTORIGVENPAG, A.IDERROS, A.IDAVISOS, A.CDFILIEMIT, A.IDORIGDESTNF AS IDORIGDESTOP,
       F.NMFILIAL AS NMFILFORCLIE, A.CDOPERGERA, B.QTDIASVENPAG, ITP.QTITEMPROD, ITP.VRUNITITEM,  A.VRNOTAFISC, 
       A.VRNOTAFISC/COUNT(A.NRLANCTONF) OVER (PARTITION BY EM.NRORG, EM.CDEMPRESA, F.CDFILIAL, A.NRLANCTONF, A.DTEMISSAO) AS VRTOTAL, ITP.VRBRUTITEM AS VRTOTAITEM,
       (SELECT MAX(FAM.NMPRODUTO) FROM PRODUTO FAM WHERE FAM.CDNVPRODUTO = '1' AND PR.CDARVPROD LIKE FAM.CDARVPROD || '%') AS NMSUBPRODNIVEL
      FROM NOTAFISCAL A 
         JOIN CONTAPAGAR B
            ON (A.CDFILIAL = B.CDFILIAL)                         
            AND (A.NRLANCTONF = B.NRLANCTONF)  
         JOIN TIPOOPERAC C
            ON (A.IDENTRSAIDOP = C.IDENTRSAIDOP)
            AND (A.CDTIPOOPER = C.CDTIPOOPER) 
         JOIN FILIAL F
            ON (A.CDFILIRECE = F.CDFILIAL)
            AND (F.CDFILIAL = A.CDFILIEMIT)
         JOIN EMPRESA EM
            ON (EM.CDEMPRESA = A.CDEMPRESA)
         JOIN ITEMPRODUTO ITP
            ON (A.NRLANCTONF = ITP.NRLANCTONF)    
            AND (A.CDFILIAL = ITP.CDFILIAL)
         JOIN PRODUTO PR
            ON (ITP.CDPRODUTO = PR.CDPRODUTO)
      WHERE
       (TO_DATE(TO_CHAR(A.DTEMISSAO,'DD/MM/YYYY')) BETWEEN TO_DATE(:START_DATE, 'DD/MM/YYYY') AND TO_DATE(:END_DATE, 'DD/MM/YYYY'))              AND
       (C.IDENTRSAIDOP        = 'E')                                  AND
       (A.IDORIGDESTNF = 'L')                                         AND
       ((A.IDSISTEMA IN ('EST','DFE') OR IDSISTEMA IS NULL))          AND
       (A.CDFILIRECE <> A.CDFILIEMIT)                                 AND
       (A.IDSTATUS NOT IN ('I', 'L', 'D'))
       
    UNION ALL
    
    SELECT DISTINCT EM.NRORG, EM.CDEMPRESA, EM.NMEMPRESA, F.CDFILIAL,   DECODE(F.CDFILIAL, '', '', F.NMFILIAL) NMFILIAL,
       A.DTENTRSAID, A.DTEMISSAO,  TO_CHAR(A.DTENTRSAID, 'MON/YYYY')AS PERIODO, TO_CHAR(A.DTENTRSAID, 'YYYY')AS ANO, TO_CHAR(A.DTENTRSAID, 'MON')AS DSMES,
       TO_CHAR(A.DTENTRSAID, 'MM')AS NRMES, TRUNC(A.DTENTRSAID, 'MM')AS DTMES, TO_CHAR(A.DTENTRSAID,'Q')||'° Trimestre'AS TRIMES, SUBSTR(C.NMTIPOOPER,1,14) AS NMTIPOOPER,
       A.NRNOTAFISC, A.CDSERIEENTR, A.IDTPIJURNF, A.NRINSJURNF, A.NRLANCTONF, PR.CDPRODUTO, PR.NMPRODUTO, PR.SGUNIDADE, B.DTORIGVENPAG, A.IDERROS, A.IDAVISOS, A.CDFILIEMIT, A.IDORIGDESTNF AS IDORIGDESTOP,
       F.NMFILIAL AS NMFILFORCLIE, A.CDOPERGERA, B.QTDIASVENPAG, ITP.QTITEMPROD, ITP.VRUNITITEM,  A.VRNOTAFISC, 
       A.VRNOTAFISC/COUNT(A.NRLANCTONF) OVER (PARTITION BY EM.NRORG, EM.CDEMPRESA, F.CDFILIAL, A.NRLANCTONF, A.DTEMISSAO) AS VRTOTAL, ITP.VRBRUTITEM AS VRTOTAITEM,
       (SELECT MAX(FAM.NMPRODUTO) FROM PRODUTO FAM WHERE FAM.CDNVPRODUTO = '1' AND PR.CDARVPROD LIKE FAM.CDARVPROD || '%') AS NMSUBPRODNIVEL
    FROM NOTAFISCAL A
         JOIN EMPRESA EM
            ON (EM.CDEMPRESA = A.CDEMPRESA)    
         LEFT JOIN CONTAPAGAR B -- Alterado para LEFT JOIN
            ON (A.CDFILIAL = B.CDFILIAL)                              
            AND (A.NRLANCTONF = B.NRLANCTONF)   
         JOIN TIPOOPERAC C
            ON (A.IDENTRSAIDOP = C.IDENTRSAIDOP) 
            AND (A.CDTIPOOPER = C.CDTIPOOPER) 
         JOIN FILIAL F
            ON (A.CDFILIRECE = F.CDFILIAL)   
         JOIN CLIENTE CL
            ON (CL.CDCLIENTE = A.CDCLIENTE)    
         JOIN ITEMPRODUTO ITP
            ON (A.NRLANCTONF = ITP.NRLANCTONF)    
            AND (A.CDFILIAL = ITP.CDFILIAL)       
         JOIN PRODUTO PR
            ON (ITP.CDPRODUTO = PR.CDPRODUTO)      
    WHERE
       (TO_DATE(TO_CHAR(A.DTEMISSAO,'DD/MM/YYYY')) BETWEEN TO_DATE(:START_DATE, 'DD/MM/YYYY') AND TO_DATE(:END_DATE, 'DD/MM/YYYY'))     AND
       (C.IDENTRSAIDOP = 'E')                                         AND
       (A.IDORIGDESTNF = 'C')                                  AND 
       ((A.IDSISTEMA IN ('EST','DFE') OR IDSISTEMA IS NULL))   AND
       (A.IDSTATUS NOT IN ('I', 'L', 'D'))
   
    UNION ALL
    
    SELECT DISTINCT EM.NRORG, EM.CDEMPRESA, EM.NMEMPRESA,  F.CDFILIAL, DECODE(F.CDFILIAL, '', '', F.NMFILIAL) NMFILIAL,
       A.DTENTRSAID, A.DTEMISSAO,  TO_CHAR(A.DTENTRSAID, 'MON/YYYY')AS PERIODO, TO_CHAR(A.DTENTRSAID, 'YYYY')AS ANO, TO_CHAR(A.DTENTRSAID, 'MON')AS DSMES,
       TO_CHAR(A.DTENTRSAID, 'MM')AS NRMES, TRUNC(A.DTENTRSAID, 'MM')AS DTMES, TO_CHAR(A.DTENTRSAID,'Q')||'° Trimestre'AS TRIMES, SUBSTR(C.NMTIPOOPER,1,14) AS NMTIPOOPER,
       A.NRNOTAFISC, A.CDSERIEENTR, A.IDTPIJURNF, A.NRINSJURNF, A.NRLANCTONF, PR.CDPRODUTO, PR.NMPRODUTO, PR.SGUNIDADE, B.DTORIGVENPAG, A.IDERROS, A.IDAVISOS, A.CDFILIEMIT, A.IDORIGDESTNF AS IDORIGDESTOP,
       FO.NMRAZSOCFORN AS NMFILFORCLIE, A.CDOPERGERA, B.QTDIASVENPAG, ITP.QTITEMPROD, ITP.VRUNITITEM,  A.VRNOTAFISC, 
       A.VRNOTAFISC/COUNT(A.NRLANCTONF) OVER (PARTITION BY EM.NRORG, EM.CDEMPRESA, F.CDFILIAL, A.NRLANCTONF, A.DTEMISSAO) AS VRTOTAL, ITP.VRBRUTITEM AS VRTOTAITEM,
       (SELECT MAX(FAM.NMPRODUTO) FROM PRODUTO FAM WHERE FAM.CDNVPRODUTO = '1' AND PR.CDARVPROD LIKE FAM.CDARVPROD || '%') AS NMSUBPRODNIVEL
    FROM NOTAFISCAL A
         LEFT JOIN CONTAPAGAR B -- Alterado para LEFT JOIN
            ON (A.CDFILIAL = B.CDFILIAL)                                      
            AND (A.NRLANCTONF = B.NRLANCTONF) 
         JOIN TIPOOPERAC C
            ON (A.IDENTRSAIDOP = C.IDENTRSAIDOP)
            AND (A.CDTIPOOPER = C.CDTIPOOPER) 
         JOIN FILIAL F
            ON (A.CDFILIRECE = F.CDFILIAL)
         JOIN EMPRESA EM
            ON (EM.CDEMPRESA = A.CDEMPRESA)
         JOIN FORNECEDOR FO
            ON (FO.CDFORNECED = A.CDFORNECED)
         JOIN ITEMPRODUTO ITP
            ON (A.NRLANCTONF = ITP.NRLANCTONF)    
            AND (A.CDFILIAL = ITP.CDFILIAL)
         JOIN PRODUTO PR
            ON (ITP.CDPRODUTO = PR.CDPRODUTO)
    WHERE
       (TO_DATE(TO_CHAR(A.DTEMISSAO,'DD/MM/YYYY')) BETWEEN TO_DATE(:START_DATE, 'DD/MM/YYYY') AND TO_DATE(:END_DATE, 'DD/MM/YYYY'))     AND
       (C.IDENTRSAIDOP = 'E')                                         AND
       (A.IDORIGDESTNF = 'F')                                         AND
       ((A.IDSISTEMA IN ('EST','DFE') OR IDSISTEMA IS NULL))          AND
       (A.IDSTATUS NOT IN ('I', 'L', 'D'))) N
    JOIN ORGANIZACAO ORG
        ON (N.NRORG = ORG.NRORG)
		AND N.IDTPIJURNF='J'