SELECT E.NRORG, ORG.NMORGANIZACAO, N.CDEMPRESA, E.NMEMPRESA, N.CDFILIAL, FI.NMFILIAL, 
   R.CDCENTCUSNF, C.NMCENTCUST, N.CDTIPOOPER, N.CDFORNECED, F.IDTPIJURFORN, 
   N.NRLANCTONF, N.DSCDFISOPENF, N.CDFISOPENTF, 
   P.CDPRODUTO, P.NMPRODUTO, P.CDARVPROD, I.NRSEQITPROD,
   TO_CHAR(N.DTENTRSAID, 'MON/YYYY') AS MES, 
   TO_CHAR(N.DTENTRSAID, 'YYYY') AS ANO, 
   TO_CHAR(N.DTENTRSAID, 'MON') AS DSMES,
   TO_CHAR(N.DTENTRSAID, 'MM') AS NRMES, 
   TO_CHAR(N.DTENTRSAID, 'Q') || '° Trimestre' AS TRIMES, 
   F.NRINSJURFORN, F.NMRAZSOCFORN, N.CDSERIEENTR, R.CDFILICCUST, 
   N.NRNOTAFISC, N.DTEMISSAO, N.DTENTRSAID, N.CDFILIRECE, 
   R.VRRATENF AS VRRATEIO,

   -- Valor líquido total da nota (sempre o total real)
   ROUND((SELECT SUM(I2.VRCONTITEM) 
          FROM ITEMPRODUTO I2 
          WHERE I2.CDFILIAL   = N.CDFILIAL
            AND I2.NRLANCTONF = N.NRLANCTONF), 2) AS VRLIQ,

   -- QTDNOTAS: 1 apenas na PRIMEIRA linha da nota, 0 nas demais
   -- Assim SUM(QTDNOTAS) no Power BI dá a contagem real de notas
   CASE 
       WHEN ROW_NUMBER() OVER (
                PARTITION BY N.CDFILIAL, N.NRLANCTONF 
                ORDER BY I.NRSEQITPROD, R.CDCENTCUSNF
            ) = 1 
       THEN 1 ELSE 0 
   END AS QTDNOTAS,

   -- VRLIQTOTAL: total da nota apenas na PRIMEIRA linha, 0 nas demais
   -- Assim SUM(VRLIQTOTAL) no Power BI dá o líquido real sem duplicar
   CASE 
       WHEN ROW_NUMBER() OVER (
                PARTITION BY N.CDFILIAL, N.NRLANCTONF 
                ORDER BY I.NRSEQITPROD, R.CDCENTCUSNF
            ) = 1 
       THEN ROUND((SELECT SUM(I2.VRCONTITEM) 
                   FROM ITEMPRODUTO I2 
                   WHERE I2.CDFILIAL   = N.CDFILIAL
                     AND I2.NRLANCTONF = N.NRLANCTONF), 2)
       ELSE 0 
   END AS VRLIQTOTAL,

   I.QTITEMPROD, 
   I.VRUNITITEM,
   ROUND(I.QTITEMPROD * I.VRUNITITEM, 2) AS VRTOT_BRUTO,

   -- VRTOT_LIQUIDO: rateado proporcionalmente pelo VRRATENF
   -- Se o item se divide em N rateios, cada linha pega sua fatia
   ROUND(
       I.VRCONTITEM * (R.VRRATENF / NULLIF(
           SUM(R.VRRATENF) OVER (
               PARTITION BY I.CDFILIAL, I.NRLANCTONF, I.NRSEQITPROD
           ), 0)
       ), 2
   ) AS VRTOT_LIQUIDO,

   N.VRNOTAFISC

FROM NOTAFISCAL N
    JOIN FORNECEDOR F      ON F.CDFORNECED = N.CDFORNECED(+)
    JOIN EMPRESA E         ON E.CDEMPRESA  = N.CDEMPRESA
    JOIN ORGANIZACAO ORG   ON E.NRORG      = ORG.NRORG
    JOIN ITEMPRODUTO I     ON N.CDFILIAL   = I.CDFILIAL
                          AND N.NRLANCTONF = I.NRLANCTONF
    JOIN PRODUTO P         ON I.CDPRODUTO  = P.CDPRODUTO
    JOIN RATEIONF R        ON I.CDFILIAL    = R.CDFILIAL
                          AND I.NRLANCTONF  = R.NRLANCTONF
                          AND I.NRSEQITPROD = R.NRSEQITPROD
    JOIN FILIAL FI         ON FI.CDFILIAL  = R.CDFILICCUST
    JOIN CENTCUST C        ON C.CDCENTCUST = R.CDCENTCUSNF
    JOIN TIPOOPERAC TP     ON TP.CDTIPOOPER = N.CDTIPOOPER

WHERE N.IDENTRSAIDOP  = 'E'
  AND TP.IDENTRSAIDOP = 'E'
  AND N.CDTIPOOPER IN ('01','15','19','20','22','23','24','26','28','29','40','43','45','46','58')
  AND TO_DATE(TO_CHAR(N.DTEMISSAO,'DD/MM/YYYY')) 
      BETWEEN TO_DATE(:START_DATE, 'DD/MM/YYYY') 
          AND TO_DATE(:END_DATE,   'DD/MM/YYYY')